[phases.setup]
nixPkgs = ['nodejs', 'python39']

[phases.install]
cmds = [
    'cd frontend && npm install',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'cd frontend && npm run build'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT main:application'