from flask import Flask, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

AGENDA = [
    {"horario": "08:00", "funcionario": "jean", "tarefa": "suporte"},
    {"horario": "09:00", "funcionario": "guido", "tarefa": "checkins"},
    {"horario": "09:00", "funcionario": "pedro", "tarefa": "checkins"},
    {"horario": "09:00", "funcionario": "dayana", "tarefa": "social_selling"},
    {"horario": "09:00", "funcionario": "jean", "tarefa": "suporte"},
    {"horario": "09:30", "funcionario": "guido", "tarefa": "reuniao_diaria"},
    {"horario": "09:30", "funcionario": "pedro", "tarefa": "reuniao_diaria"},
    {"horario": "09:30", "funcionario": "dayana", "tarefa": "reuniao_diaria"},
    {"horario": "09:30", "funcionario": "jean", "tarefa": "suporte"},
    {"horario": "10:00", "funcionario": "guido", "tarefa": "reuniao_diaria"},
    {"horario": "10:00", "funcionario": "pedro", "tarefa": "reuniao_diaria"},
    {"horario": "10:00", "funcionario": "dayana", "tarefa": "reuniao_diaria"},
    {"horario": "10:00", "funcionario": "jean", "tarefa": "suporte"},
    {"horario": "10:30", "funcionario": "guido", "tarefa": "checkins"},
    {"horario": "10:30", "funcionario": "pedro", "tarefa": "checkins"},
    {"horario": "10:30", "funcionario": "dayana", "tarefa": "engajamento_grupo"},
    {"horario": "10:30", "funcionario": "jean", "tarefa": "suporte"},
    {"horario": "11:00", "funcionario": "guido", "tarefa": "checkins"},
    {"horario": "11:00", "funcionario": "pedro", "tarefa": "checkins"},
    {"horario": "11:00", "funcionario": "jean", "tarefa": "suporte"},
    {"horario": "11:00", "funcionario": "thais", "tarefa": "checkins"},
    {"horario": "11:30", "funcionario": "guido", "tarefa": "montar_planos"},
    {"horario": "11:30", "funcionario": "pedro", "tarefa": "checkins"},
    {"horario": "11:30", "funcionario": "thais", "tarefa": "montar_planos"},
    {"horario": "13:00", "funcionario": "guido", "tarefa": "suporte"},
    {"horario": "13:00", "funcionario": "michelle", "tarefa": "checkins"},
    {"horario": "13:00", "funcionario": "dayana", "tarefa": "social_selling"},
    {"horario": "13:30", "funcionario": "guido", "tarefa": "separar_alunos"},
    {"horario": "13:30", "funcionario": "michelle", "tarefa": "checkins"},
    {"horario": "13:30", "funcionario": "dayana", "tarefa": "social_selling"},
    {"horario": "14:00", "funcionario": "guido", "tarefa": "separar_alunos"},
    {"horario": "14:00", "funcionario": "michelle", "tarefa": "engajamento_grupo"},
    {"horario": "14:00", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "14:30", "funcionario": "guido", "tarefa": "separar_alunos"},
    {"horario": "14:30", "funcionario": "michelle", "tarefa": "engajamento_grupo"},
    {"horario": "14:30", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "15:00", "funcionario": "pedro", "tarefa": "material_renovacao"},
    {"horario": "15:00", "funcionario": "michelle", "tarefa": "engajamento_grupo"},
    {"horario": "15:00", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "15:30", "funcionario": "pedro", "tarefa": "material_renovacao"},
    {"horario": "15:30", "funcionario": "michelle", "tarefa": "material_renovacao"},
    {"horario": "15:30", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "16:00", "funcionario": "pedro", "tarefa": "material_renovacao"},
    {"horario": "16:00", "funcionario": "michelle", "tarefa": "material_renovacao"},
    {"horario": "16:00", "funcionario": "dayana", "tarefa": "engajamento_alunos"},
    {"horario": "16:00", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "16:30", "funcionario": "pedro", "tarefa": "checkins"},
    {"horario": "16:30", "funcionario": "michelle", "tarefa": "material_renovacao"},
    {"horario": "16:30", "funcionario": "dayana", "tarefa": "checkins"},
    {"horario": "16:30", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "17:00", "funcionario": "pedro", "tarefa": "checkins"},
    {"horario": "17:00", "funcionario": "michelle", "tarefa": "suporte"},
    {"horario": "17:00", "funcionario": "dayana", "tarefa": "social_selling"},
    {"horario": "17:00", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "17:00", "funcionario": "thais", "tarefa": "checkins"},
    {"horario": "17:30", "funcionario": "pedro", "tarefa": "checkins"},
    {"horario": "17:30", "funcionario": "michelle", "tarefa": "suporte"},
    {"horario": "17:30", "funcionario": "dayana", "tarefa": "social_selling"},
    {"horario": "17:30", "funcionario": "andreia", "tarefa": "suporte"},
    {"horario": "17:30", "funcionario": "thais", "tarefa": "montar_planos"}
]

def handler(request):
    return jsonify(AGENDA)